# Generated by Django 5.1.2 on 2024-11-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clave', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Linea', models.CharField(max_length=255)),
                ('existencias', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
