# Generated by Django 5.1.2 on 2024-11-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_producst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producst',
            new_name='Products',
        ),
    ]
